### ISSUE TITLE
Environment variable exported with `env.sh` is not effective

### ISSUE THREAD

**Issue by zhangysh1995** [DBCobra/CobraHome#1]
As described in the README file:

> Cobra requires Java v1.8.0 (or higher). After you install the Java environment, update JAVA_HOME in the file env.sh:
> 
> export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
> Cobra verifier requires CUDA. After you install CUDA, update CUDA_PATH in the file env.sh:
> 
> export CUDA_PATH="/usr/local/cuda"

However, these environment variables will have NO effect on the user's default bash because they are only set for the *boxed bash* which actually runs this script. I realized this problem when I tried to run the `mvn` command for `CobraVerifier` which requires these two variables.

I think it's better to point the user to export the environment variables in their bash by explicitly running `export xx`.

**Comment by zhangysh1995** [comment]
If my suggestion is considered useful, I can submit a PR for the README.

**Comment by naizhengtan** [comment]
Hi Yushan, thank you for the comments.

We specify that people should source `env.sh` when they run the verifier, as suggested in [step 0](https://github.com/DBCobra/CobraVerifier#step-0-setup-environment) in the verifier's README. Therefore, people should have their environment variables ready when running `mvn`.

Also, thank you for the pull request. It's a nice trick if you want Cobra's variables in all your terminal environments. But generally, I don't think this is a good idea for everyone because `.bashrc`'s space is precious (at least for me).

Please feel free to let me know what you think.

**Comment by zhangysh1995** [comment]
The problem here is that running `env.sh` is not setting the bash's environment variable, which is run and then the update is thrown away. Because I did exactly the thing as described in the README and the environment variables are gone. Maybe you could try again to run the script and verify what I claimed as "the settings are thrown away"?

**Comment by naizhengtan** [comment]
> The problem here is that running `env.sh` is not setting ...

I see. We need people to *source* `env.sh` instead of *running* it.
The dot `.` in the [step 1](https://github.com/DBCobra/CobraHome#step-1-create-environment) is a source command (see more about source command in this [blog](https://linuxize.com/post/bash-source-command/)).
I will update our README by explicitly using `source` to avoid such confusion.
